### ISSUE TITLE
Any example code for buttons

### ISSUE THREAD

**Issue by iamit06** [xatkit-bot-platform/xatkit-react-platform#16]
Hi, I am unable to use button in intend and execution to provide a button and trigger an action. Please provide example code.

**Comment by gdaniel** [comment]
Hi,
From the documentation, you can provide two parameters to the `ReactPlatform.Reply` action
- message (String): the message to post as a reply
- buttons (List[String], Optional): a list of values to render as quick message buttons
In your execution model it would look like
```
ReactPlatform.Reply("Are you interested in our product?", #["Yes", "No"])
```
Note that you need to define intents matching the buttons content, e.g.
```
intent Yes {
  inputs {
    "Yes"
  }
}
intent No {
  inputs {
    "No"
  }
}
```

**Comment by iamit06** [comment]
Thanks Daniel, for quick response.
The above code snippets helped a lot.
